function createfigure(XData1, YData1, XData2, YData2, XData3, YData3, XData4, YData4, XData5, YData5, XData6, YData6, XData7, YData7)
%CREATEFIGURE(XData1, YData1, XData2, YData2, XData3, YData3, XData4, YData4, XData5, YData5, XData6, YData6, XData7, YData7)
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  XDATA2:  line xdata
%  YDATA2:  line ydata
%  XDATA3:  line xdata
%  YDATA3:  line ydata
%  XDATA4:  line xdata
%  YDATA4:  line ydata
%  XDATA5:  line xdata
%  YDATA5:  line ydata
%  XDATA6:  line xdata
%  YDATA6:  line ydata
%  XDATA7:  line xdata
%  YDATA7:  line ydata

%  Auto-generated by MATLAB on 08-Jun-2019 17:17:42

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.144354066985646 0.11 0.760645933014354 0.768917050691244]);
hold(axes1,'on');

% Create line
line(XData1,YData1,'Visible','off','Parent',axes1);

% Create hggroup
hggroup1 = hggroup('DisplayName','K = 4','Parent',axes1);

% Create line
line(XData2,YData2,'Parent',hggroup1,'LineWidth',2,...
    'Color',[0 0.498039215686275 0]);

% Create line
line(XData3,YData3,'Parent',hggroup1,'LineWidth',2,...
    'Color',[0 0.498039215686275 0]);

% Create hggroup
hggroup2 = hggroup('DisplayName','K = 8','Parent',axes1);

% Create line
line(XData4,YData4,'Parent',hggroup2,'LineWidth',2,...
    'Color',[0 0.447058823529412 0.741176470588235]);

% Create line
line(XData5,YData5,'Parent',hggroup2,'LineWidth',2,...
    'Color',[0 0.447058823529412 0.741176470588235]);

% Create hggroup
hggroup3 = hggroup('DisplayName','K = 12','Parent',axes1);

% Create line
line(XData6,YData6,'Parent',hggroup3,'LineWidth',2,'Color',[1 0 0]);

% Create line
line(XData7,YData7,'Parent',hggroup3,'LineWidth',2,'Color',[1 0 0]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-4 12]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-9 2]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XColor',[0.4 0.4 0.4],'YColor',[0.4 0.4 0.4]);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.752791070042139 0.740399388650778 0.110047845428355 0.115207370181787]);

% Create ylabel
ylabel('Imaginary Axis','HitTest','off','Units','pixels',...
    'HorizontalAlignment','center',...
    'FontAngle','italic',...
    'FontSize',11,...
    'Visible','on');

% Create xlabel
xlabel('Real Axis','HitTest','off','Units','pixels',...
    'HorizontalAlignment','center',...
    'FontAngle','italic',...
    'FontSize',11,...
    'Visible','on');

% Create title
title('Nyquist Diagram','HitTest','off','Units','pixels',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',11);

